version: "3.7"

services:
    lolisafe:
        build:
            context: ../
            dockerfile: ./docker/lolisafe/Dockerfile
        expose:
            - "9999"
        restart: unless-stopped
        environment:
            PORT: 9999
            DOMAIN: ''
            HOME_DOMAIN: ''
